// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package models

// ホストのCPU情報
type Cpu struct {
	Counts  int     `json:"counts"`
	Percent float64 `json:"percent"`
}

// Devices defines model for Devices.
type Devices struct {
	Disk []Disk `json:"disk"`
}

// Disk defines model for Disk.
type Disk struct {
	Device string `json:"device"`
	Path   string `json:"path"`
	Type   string `json:"type"`
}

// ホストのメモリ情報
type Memory struct {
	Free        uint64  `json:"free"`
	Total       uint64  `json:"total"`
	Used        uint64  `json:"used"`
	UsedPercent float64 `json:"used_percent"`
}

// Metadata defines model for Metadata.
type Metadata struct {
	ApiVersion string `json:"api_version"`
	Id         string `json:"id"`
}

// ホストが持つストレージプールの情報
type StoragePool struct {
	Name      string `json:"name"`
	Path      string `json:"path"`
	Status    string `json:"status"`
	TotalSize uint64 `json:"total_size"`
	UsedSize  uint64 `json:"used_size"`
}

// 仮想マシンを表すモデル
type Vm struct {
	Devices  Devices  `json:"devices"`
	Memory   int      `json:"memory"`
	Metadata Metadata `json:"metadata"`
	Name     string   `json:"name"`
	Vcpu     int      `json:"vcpu"`
}

// PostApiV1VmsJSONBody defines parameters for PostApiV1Vms.
type PostApiV1VmsJSONBody struct {
	Memory int    `json:"memory"`
	Name   string `json:"name"`
	Vcpu   int    `json:"vcpu"`
}

// PatchApiV1VmsVmIdJSONBody defines parameters for PatchApiV1VmsVmId.
type PatchApiV1VmsVmIdJSONBody struct {
	Memory *int    `json:"memory,omitempty"`
	Name   *string `json:"name,omitempty"`
	Vcpu   *int    `json:"vcpu,omitempty"`
}

// PostApiV1VmsJSONRequestBody defines body for PostApiV1Vms for application/json ContentType.
type PostApiV1VmsJSONRequestBody PostApiV1VmsJSONBody

// PatchApiV1VmsVmIdJSONRequestBody defines body for PatchApiV1VmsVmId for application/json ContentType.
type PatchApiV1VmsVmIdJSONRequestBody PatchApiV1VmsVmIdJSONBody
